In [1]:
import numpy as np 

# The Data 

In [2]:
# Read the file, using newline as the delimiter
d2_input = np.genfromtxt("d2_input.txt", delimiter="\n", dtype=str, encoding="utf-8")
d2_input = [np.array(line.split(),dtype=int) for line in d2_input]
d2_input[:5]

[array([ 6,  8, 11, 12, 14, 16, 18, 16]),
 array([73, 76, 79, 80, 81, 84, 86, 86]),
 array([32, 33, 34, 37, 40, 44]),
 array([ 9, 11, 13, 14, 17, 24]),
 array([59, 61, 64, 62, 65])]

# Part One 

Simple solution for part one, could probably be much faster if I knew fancy algos. 

In [3]:
unsafe = 0
for report in d2_input:
    for index in range(len(report)-1):
        
        
        if index == 0:
            pass
        elif index != 0:
            prev    = report[index-1] - report[index]
            nextv   = report[index] - report[index+1]
            #Check if increasing on one side and decreasing on other
            if ((prev <= 0) and (nextv >= 0)) or ((prev >= 0) and (nextv <=0)):
                unsafe += 1
                break
            elif (np.abs(prev) > 3) or (np.abs(nextv) > 3):
                unsafe += 1
                break
                #Check if the increase/decrease is too big:
                
    safe = len(d2_input) - unsafe
safe 
            

442

# Part Two 

In [4]:
def rule_break(prev,curr,nextv): #Returns true if a rule broken 

    if np.isnan(prev): #We are at the beginning:
        if np.abs(curr-nextv) > 3:
            return True 
    if np.isnan(nextv): #We are at the end
        if np.abs(prev-curr) > 3:
            return True
    if prev == curr or curr == nextv: #Check if they're the same 
        return True
    if (prev - curr <= 0) and (curr - nextv >=0):
        return True
    if (prev - curr >=0) and (curr - nextv <=0):
        return True 
    if np.abs(prev-curr)>3:
        return True
    if np.abs(curr-nextv) >3:
        return True
    else:
        return False # Pass

In [5]:
# A dirty method of dampening 

safe = 0
breaking_list = []
test = [np.array([7,6,4,2,1]),
        np.array([1,2,7,8,9]),
        np.array([9,7,6,2,1]),
        np.array([1,3,2,4,5]),
        np.array([8,6,4,4,1]),
        np.array([1,3,6,7,9])]
def satisfies_rules(report):
    for index in range(len(report)-1):
        if index == 0: #At the beginning 
            if rule_break(np.nan,report[index],report[index+1]):
                
                return False
                break
            else:
                continue
        else: #Not at beginning 
            if rule_break(report[index-1],report[index],report[index+1]):
                return False
                break
            else:
                continue

    return True
for report in d2_input:
    if satisfies_rules(report):
        safe +=1
    else:
        for i in range(len(report)):
            if satisfies_rules(np.delete(report,i)):
                safe += 1
                break
safe
                

493