In [1]:
import numpy as np

In [2]:
rules = np.genfromtxt('d5_rules.txt',delimiter='|',dtype=int)
rules[:5]

array([[96, 15],
       [69, 95],
       [69, 66],
       [41, 61],
       [41, 26]])

In [6]:
rules.shape

(1176, 2)

In [3]:
d5_input = open('d5_input.txt')
d5_input = d5_input.readlines().copy()
d5_input[:5]

['27,51,67,91,42,86,58,66,39,72,96\n',
 '88,64,61,72,82,46,36,63,41,95,75\n',
 '17,62,58,66,79,22,39,72,19,96,65,63,12,41,25,46,64,75,11,95,99,23,61\n',
 '12,41,39,93,95,66,86,62,42,11,58\n',
 '18,92,26,48,67,83,69,42,62,58,66,79,39,19,15\n']

In [4]:
np.fromstring(d5_input[0],sep=',',dtype=int)

array([27, 51, 67, 91, 42, 86, 58, 66, 39, 72, 96])

In [5]:
d5_array = [np.fromstring(line, sep=',', dtype=int) for line in d5_input]
d5_array[:5]

[array([27, 51, 67, 91, 42, 86, 58, 66, 39, 72, 96]),
 array([88, 64, 61, 72, 82, 46, 36, 63, 41, 95, 75]),
 array([17, 62, 58, 66, 79, 22, 39, 72, 19, 96, 65, 63, 12, 41, 25, 46, 64,
        75, 11, 95, 99, 23, 61]),
 array([12, 41, 39, 93, 95, 66, 86, 62, 42, 11, 58]),
 array([18, 92, 26, 48, 67, 83, 69, 42, 62, 58, 66, 79, 39, 19, 15])]

In [17]:
after_mask = np.isin(rules[:,0],d5_array[0]) # Rules requiring numbers to be after
after_rules = rules[after_mask]

before_mask = np.isin(rules[:,1], d5_array[0])
before_rules = rules[before_mask]


In [36]:
rules[np.any(after_mask,before_mask)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [20]:
after_rules[:5][0]

array([96, 15])

In [ ]:
d5_array[

In [44]:
test_array = d5_array[0]
for i in range(len(test_array)):
    
    value = d5_array[0][i] 
    
    for rule in after_rules: #Iterate through after rules 
        
        if value == rule[1]:
            breaks_rule = np.isin(test_array[i:], rule[0]) 
            if np.any(breaks_rule):
                
                print('after rule_broken at index i', i)
                print('rule', rule)
                
    for rule in before_rules: #Iterate through before rules
        
        if value == rule[1]:
            breaks_rule = np.isin(test_array[:i], rule[0])
            
            if np.any(breaks_rule):
                print('before rule_broken at index i',i)
                print('rule', rule)
    
            
            
d5_array[0]

after rule_broken at index i 0
rule [27 91]
after rule_broken at index i 0
rule [27 66]
after rule_broken at index i 0
rule [27 96]
after rule_broken at index i 0
rule [27 72]
after rule_broken at index i 0
rule [27 67]
after rule_broken at index i 0
rule [27 39]
after rule_broken at index i 0
rule [27 86]
after rule_broken at index i 0
rule [27 42]
after rule_broken at index i 0
rule [27 58]
after rule_broken at index i 0
rule [27 51]
after rule_broken at index i 1
rule [51 58]
after rule_broken at index i 1
rule [51 67]
after rule_broken at index i 1
rule [51 39]
after rule_broken at index i 1
rule [51 86]
after rule_broken at index i 1
rule [51 42]
after rule_broken at index i 1
rule [51 91]
after rule_broken at index i 1
rule [51 66]
after rule_broken at index i 1
rule [51 72]
after rule_broken at index i 1
rule [51 96]
before rule_broken at index i 1
rule [27 51]
after rule_broken at index i 2
rule [67 91]
after rule_broken at index i 2
rule [67 58]
after rule_broken at index i 2


array([27, 51, 67, 91, 42, 86, 58, 66, 39, 72, 96])

In [ ]:
# Check if the second page is in the rules


In [22]:
np.any(before_mask)

np.True_