In [1]:
import numpy as np

In [2]:
d6_input = open('d6_input.txt')
d6_input = d6_input.readlines().copy()
d6_input = np.array([list(line.strip()) for line in d6_input])
d6_input[:5,:5]

array([['.', '.', '#', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['#', '.', '.', '.', '.']], dtype='<U1')

# Part One 

In [3]:
hashtags = np.where(d6_input =='#')
starting_spot = np.where(d6_input == '^')
starting_spot

(array([37]), array([65]))

In [8]:
def path_maker(input_array):
    
    starting_spot = np.where(input_array == '^')
    path = input_array.copy()
    current_spot = starting_spot
    is_in_bounds =  0 <= current_spot[0] < input_array.shape[0] and 0 <= current_spot[1] < input_array.shape[1]
    character = '^'
    steps = 0
    while is_in_bounds:
        i , j = current_spot
        try:
            if character == '>': 
                
                if input_array[i,j+1] == '#':
                    character = 'v'
                    continue
                else:
                    path[current_spot] = 'X'
                    steps +=1
                    current_spot = (i,j+1)
            if character == 'v': 
                if input_array[i+1,j] == '#':
                    character = '<'
                    continue
                else:
                    path[current_spot] = 'X'
                    steps += 1
                    current_spot = (i+1,j)    
            if character =='<': 
                if input_array[i,j-1] =='#':
                    character = '^'
                    continue
                else:
                    path[current_spot] = 'X'
                    steps += 1
                    current_spot = (i,j-1)
            if character == '^': 
                if input_array[i-1,j] == '#':
                    character = '>'
                    continue
                else:
                    path[current_spot] = 'X'
                    steps +=1
                    current_spot = (i-1,j)
        except:
            is_in_bounds = False 
    return steps, path
            
path_maker(d6_input)[0]

5950

In [9]:
np.savetxt('d6_path.txt',path_maker(d6_input)[1],fmt='%s')

# Part Two 

In [12]:
d6_test = open('d6_test.txt')
d6_test = d6_test.readlines().copy()
d6_test = np.array([list(line.strip()) for line in d6_test])
d6_test[:5,:5]

array([['.', '.', '.', '.', '#'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '#', '.', '.'],
       ['.', '.', '.', '.', '.']], dtype='<U1')

In [13]:
#path = d6_test.copy()
#path.shape == d6_test.shape

In [27]:
130*8

1040

In [36]:
ban = {3:2,4:3}
bana = ban.copy()
bana[4] = 10
bana

{3: 2, 4: 10}

In [39]:
x = 0
while x <=5:
    print(x)
    x += 1
    if x == 3:
        break

0
1
2


In [ ]:
#Check if in loop:


In [34]:
def loop_finder(input_array, found_loops):
    
    starting_spot = np.where(input_array == '^')

    current_spot = starting_spot
    is_in_bounds = lambda x, y: 0 <= x < input_array.shape[0] and 0 <= y < input_array.shape[1]
    character = '^'
    current_loop = {}
    while is_in_bounds(*current_spot) == True :
        i , j = current_spot
        
        if found_loops[current_spot] == character: #Check if we've already found this loop
            break 
        #Check if in a loop 
        if current_loop[current_spot] == current_character:
        #In loop
            
        try:
            if character == '>': 
                
                if input_array[i,j+1] == '#':
                    character = 'v'
                    continue
                else:
                    current_loop[current_spot] = character

                    current_spot = (i,j+1)
            if character == 'v': 
                if input_array[i+1,j] == '#':
                    character = '<'
                    continue
                else:
                    current_loop[current_spot] = character

                    current_spot = (i+1,j)    
            if character =='<': 
                if input_array[i,j-1] =='#':
                    character = '^'
                    continue
                else:
                    current_loop[current_spot] = character

                    current_spot = (i,j-1)
            if character == '^': 
                if input_array[i-1,j] == '#':
                    character = '>'
                    continue
                else:
                    current_loop[current_spot] = character

                    current_spot = (i-1,j)
        except:
            is_in_bounds = False 
    return is_in_bounds #Should return false when the character exits


In [30]:
starting_spot = np.where(d6_test == '^')
d6_testloop = d6_test.copy()
d6_testloop[starting_spot,starting_spot[1]-1] = '#'
loop_finder(d6_testloop, 50)

array([ True])

In [31]:
loop_finder(d6_test, 50)

False

In [32]:
step_count, path = path_maker(d6_test)
indices = np.where(path == 'X')
blockpoints = list(zip(indices[0], indices[1]))
loop_count = 0
for blockpoint in blockpoints:
    starting_spot = np.where(d6_test == '^')
    d6_testloop = d6_test.copy()
    d6_testloop[blockpoint] = '#'
    if loop_finder(d6_testloop, step_count):
        loop_count += 1
loop_count

C:\Users\Kieran McGee\AppData\Local\Temp\ipykernel_2092\1210137950.py:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  is_in_bounds =  0 <= current_spot[0] < input_array.shape[0] and 0 <= current_spot[1] < input_array.shape[1]
C:\Users\Kieran McGee\AppData\Local\Temp\ipykernel_2092\1210137950.py:10: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  while is_in_bounds == True and steps <= maximum_steps:
C:\Users\Kieran McGee\AppData\Local\Temp\ipykernel_2092\330273880.py:9: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if loop_finder(d6_testloop, step_count):


5

In [33]:
step_count, path = path_maker(d6_input)
indices = np.where(path == 'X')
blockpoints = list(zip(indices[0], indices[1]))
loop_count = 0
for blockpoint in blockpoints:
    starting_spot = np.where(d6_input == '^')
    d6_loop = d6_input.copy()
    d6_loop[blockpoint] = '#'
    if loop_finder(d6_loop, step_count):
        loop_count += 1
loop_count

C:\Users\Kieran McGee\AppData\Local\Temp\ipykernel_2092\1210137950.py:6: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  is_in_bounds =  0 <= current_spot[0] < input_array.shape[0] and 0 <= current_spot[1] < input_array.shape[1]
C:\Users\Kieran McGee\AppData\Local\Temp\ipykernel_2092\1210137950.py:10: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  while is_in_bounds == True and steps <= maximum_steps:
C:\Users\Kieran McGee\AppData\Local\Temp\ipykernel_2092\1615466815.py:9: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if loop_finder(d6_loop, step_count):


2222

In [17]:
steps = 0
loop_count = 0
starting_spot = np.where(d6_input == '^')
indices = np.where(path == 'X')
blockpoints = list(zip(indices[0], indices[1]))

for blockpoint in blockpoints[1:]:
    current_spot = starting_spot
    current_path = d6_input.copy()
    current_path[blockpoint] = '#' #Try the blockpoint
    is_in_bounds =  True
    character = '^'
    loop_dictionary = {'>': None}
    

    while is_in_bounds:
        i , j = current_spot
        try:
            if character == '>': 
                
                if current_path[i,j+1] == '#':
                    if loop_dictionary['>'] == current_spot:
                        loop_count +=1
                        is_in_bounds = False
                        continue
                    else:
                        loop_dictionary['>'] = current_spot
                    character = 'v'
                    break
                else:
                    current_spot = (i,j+1)
                    
            if character == 'v': 
                if current_path[i+1,j] == '#':
                    character = '<'
                    continue
                else:
                    current_spot = (i+1,j)    
                    
            if character =='<': 
                if current_path[i,j-1] =='#':
                    character = '^'
                    continue
                else:
                    current_spot = (i,j-1)
            if character == '^': 
                if current_path[i-1,j] == '#':
                    character = '>'
                    continue
                else:
                    current_spot = (i-1,j)
        except:
            is_in_bounds = False 
loop_count

0

In [31]:
test_dic = {(3,2):'v'}
(3,2) in test_dic

True

In [33]:
steps = 0
loop_count = 0
starting_spot = tuple(np.argwhere(d6_input == '^')[0])  # Get starting position
indices = np.where(d6_input == 'X')
blockpoints = list(zip(indices[0], indices[1]))

for blockpoint in blockpoints[1:]:
    current_spot = starting_spot
    current_path = d6_input.copy()
    current_path[blockpoint] = '#'  # Try placing a block
    is_in_bounds = True
    character = '^'
    visited = {}  # Keep track of visited positions to detect loops

    while is_in_bounds:
        i, j = current_spot

        # Add the current position to the visited set
        if current_spot in visited:
            if visited[current_spot] == character:
                loop_count += 1
                is_in_bounds = False
                continue
        visited[current_spot] = character

        # Determine the next move based on the character's direction
        if character == '>':
            if j + 1 >= current_path.shape[1] or current_path[i, j + 1] == '#':
                character = 'v'  # Turn down
            else:
                current_spot = (i, j + 1)
        elif character == 'v':
            if i + 1 >= current_path.shape[0] or current_path[i + 1, j] == '#':
                character = '<'  # Turn left
            else:
                current_spot = (i + 1, j)
        elif character == '<':
            if j - 1 < 0 or current_path[i, j - 1] == '#':
                character = '^'  # Turn up
            else:
                current_spot = (i, j - 1)
        elif character == '^':
            if i - 1 < 0 or current_path[i - 1, j] == '#':
                character = '>'  # Turn right
            else:
                current_spot = (i - 1, j)

        # Check if the character has moved out of bounds
        if not (0 <= current_spot[0] < current_path.shape[0] and 0 <= current_spot[1] < current_path.shape[1]):
            is_in_bounds = False

print("Loop count:", loop_count)

Loop count: 0


In [35]:
d6_input.shape

(130, 130)

In [36]:
steps = 0
loop_count = 0
starting_spot = tuple(np.argwhere(d6_input == '^')[0])  # Get starting position
indices = np.where(d6_input == 'X')
blockpoints = list(zip(indices[0], indices[1]))

for blockpoint in blockpoints[1:]:
    current_spot = starting_spot
    current_path = d6_input.copy()
    current_path[blockpoint] = '#'  # Place a block at the current blockpoint
    is_in_bounds = True
    character = '^'
    visited = set()  # Track (position, direction) pairs to detect loops

    while is_in_bounds:
        i, j = current_spot

        # Check if the (position, direction) pair was already visited
        state = (current_spot, character)
        if state in visited:
            loop_count += 1
            break
        visited.add(state)

        # Determine the next move based on the character's direction
        if character == '>':
            if j + 1 < current_path.shape[1] and current_path[i, j + 1] != '#':
                current_spot = (i, j + 1)
            else:
                is_in_bounds = j + 1 < current_path.shape[1]
                if not is_in_bounds:
                    break
                character = 'v'  # Turn down
        elif character == 'v':
            if i + 1 < current_path.shape[0] and current_path[i + 1, j] != '#':
                current_spot = (i + 1, j)
            else:
                is_in_bounds = i + 1 < current_path.shape[0]
                if not is_in_bounds:
                    break
                character = '<'  # Turn left
        elif character == '<':
            if j - 1 >= 0 and current_path[i, j - 1] != '#':
                current_spot = (i, j - 1)
            else:
                is_in_bounds = j - 1 >= 0
                if not is_in_bounds:
                    break
                character = '^'  # Turn up
        elif character == '^':
            if i - 1 >= 0 and current_path[i - 1, j] != '#':
                current_spot = (i - 1, j)
            else:
                is_in_bounds = i - 1 >= 0
                if not is_in_bounds:
                    break
                character = '>'  # Turn right

print("Loop count:", loop_count)

Loop count: 0


In [19]:
np.where(path == 'X')

(array([  1,   1,   1, ..., 128, 128, 128]),
 array([37, 38, 39, ..., 48, 49, 50]))

In [20]:
d6_test.size

100