In [1]:
import numpy as np

In [2]:
d6_input = open('d6_input.txt')
d6_input = d6_input.readlines().copy()
d6_input = np.array([list(line.strip()) for line in d6_input])
d6_input[:5,:5]

array([['.', '.', '#', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.'],
       ['#', '.', '.', '.', '.']], dtype='<U1')

In [3]:
hashtags = np.where(d6_input =='#')
starting_spot = np.where(d6_input == '^')
starting_spot

(array([37]), array([65]))

In [4]:
path = d6_input.copy()
path.shape == d6_input.shape

True

In [5]:
d6_input[129,129]

np.str_('.')

In [6]:
test_array = np.array([0,4,5])
test_array[0] = 6
test_array

array([6, 4, 5])

In [7]:
starting_spot

(array([37]), array([65]))

In [8]:
path[starting_spot]
current_spot = starting_spot
is_in_bounds =  0 <= current_spot[0] < d6_input.shape[0] and 0 <= current_spot[1] < d6_input.shape[1]
character = 'v'
steps = 0
while is_in_bounds:
    i , j = current_spot
    if character == '>': 
        
        if d6_input[i,j+1] == '#':
            character = 'v'
            continue
        else:
            path[current_spot] = '>'
            steps +=1
            current_spot = (i,j+1)
    if character == 'v': 
        if d6_input[i+1,j] == '#':
            character = '<'
            continue
        else:
            path[current_spot] = 'v'
            steps += 1
            current_spot = (i+1,j)    
    if character =='<': 
        if d6_input[i,j-1] =='#':
            character = '^'
            continue
        else:
            path[current_spot] = '<'
            steps += 1
            current_spot = (i,j-1)
    if character == '^': 
        if d6_input[i-1,j] == '#':
            character = '>'
            continue
        else:
            path[current_spot] = '^'
            steps +=1
            current_spot = (i-1,j)
is_in_bounds

IndexError: index 130 is out of bounds for axis 0 with size 130

In [10]:
current_spot

(array([129]), array([29]))

In [15]:
path[starting_spot]

array(['>'], dtype='<U1')

In [13]:
np.savetxt('d6_path.txt',path,fmt='%s')

In [14]:
total_count = np.count_nonzero(np.isin(path, ['v', '<', '>', '^'])) + 1 
total_count

4620

In [16]:
path[starting_spot]
current_spot = starting_spot
is_in_bounds =  0 <= current_spot[0] < d6_input.shape[0] and 0 <= current_spot[1] < d6_input.shape[1]
character = 'v'
steps = 0
while is_in_bounds:
    i , j = current_spot
    if character == '>': 
        
        if d6_input[i,j+1] == '#':
            character = 'v'
            continue
        else:
            path[current_spot] = '*'
            steps +=1
            current_spot = (i,j+1)
    if character == 'v': 
        if d6_input[i+1,j] == '#':
            character = '<'
            continue
        else:
            path[current_spot] = '*'
            steps += 1
            current_spot = (i+1,j)    
    if character =='<': 
        if d6_input[i,j-1] =='#':
            character = '^'
            continue
        else:
            path[current_spot] = '*'
            steps += 1
            current_spot = (i,j-1)
    if character == '^': 
        if d6_input[i-1,j] == '#':
            character = '>'
            continue
        else:
            path[current_spot] = '*'
            steps +=1
            current_spot = (i-1,j)
is_in_bounds

IndexError: index 130 is out of bounds for axis 0 with size 130

In [17]:
np.sum(path == '*')

np.int64(4619)