In [1]:
import numpy as np 

# The Data 

In [2]:
# Read the file, using newline as the delimiter
d2_input = np.genfromtxt("d2_input.txt", delimiter="\n", dtype=str, encoding="utf-8")
d2_input = [np.array(line.split(),dtype=int) for line in d2_input]
d2_input[:5]

[array([ 6,  8, 11, 12, 14, 16, 18, 16]),
 array([73, 76, 79, 80, 81, 84, 86, 86]),
 array([32, 33, 34, 37, 40, 44]),
 array([ 9, 11, 13, 14, 17, 24]),
 array([59, 61, 64, 62, 65])]

In [3]:
d2_test = d2_input[:10].copy()
d2_test

[array([ 6,  8, 11, 12, 14, 16, 18, 16]),
 array([73, 76, 79, 80, 81, 84, 86, 86]),
 array([32, 33, 34, 37, 40, 44]),
 array([ 9, 11, 13, 14, 17, 24]),
 array([59, 61, 64, 62, 65]),
 array([33, 36, 37, 39, 36, 35]),
 array([60, 62, 64, 61, 62, 64, 64]),
 array([12, 15, 16, 15, 17, 18, 22]),
 array([72, 73, 75, 77, 79, 82, 79, 85]),
 array([60, 61, 64, 64, 67, 69])]

# Part One 

Simple solution for part one, could probably be much faster if I knew fancy algos. 

In [4]:
unsafe = 0
for report in d2_input:
    for index in range(len(report)-1):
        
        
        if index == 0:
            pass
        elif index != 0:
            prev    = report[index-1] - report[index]
            nextv   = report[index] - report[index+1]
            #Check if increasing on one side and decreasing on other
            if ((prev <= 0) and (nextv >= 0)) or ((prev >= 0) and (nextv <=0)):
                unsafe += 1
                break
            elif (np.abs(prev) > 3) or (np.abs(nextv) > 3):
                unsafe += 1
                break
                #Check if the increase/decrease is too big:
                
    safe = len(d2_input) - unsafe
safe 
            

442

# Part Two 

In [5]:
unsafe = 0
for report in d2_input:
    for index in range(len(report)-1):
        
        
        if index == 0:
            pass
        elif index != 0:
            prev    = report[index-1] - report[index]
            nextv   = report[index] - report[index+1]
            prev_damp = report[index-1] - report[index+1]
            try:
                next_damp = report[index+1] - report[index+2] #In case the index is out of range
            except:
                next_damp = np.nan
            
            #Check if increasing on one side and decreasing on other
            if ((prev <= 0) and (nextv >= 0)) or ((prev >= 0) and (nextv <=0)):
                #Check if Dampening works: 
                if ((prev_damp <=0) and (next_damp >= 0 and next_damp != np.nan)) or ((prev_damp >=0) and (next_damp <=0 and next_damp != np.nan)):
                    unsafe += 1
                    break
            elif (np.abs(prev) > 3) or (np.abs(nextv) > 3):
                #Check if Dampening works:
                if (np.abs(prev_damp) > 3) or (np.abs(next_damp) >3):
                    unsafe += 1
                    break
                #Check if the increase/decrease is too big:
                
    safe = len(d2_input) - unsafe
safe 

503

In [6]:
test = [np.array([7,6,4,2,1]),np.array([1,2,7,8,9]),np.array([9,7,6,2,1]),np.array([1,3,2,4,5]),np.array([8,6,4,4,1]),np.array([1,3,6,7,9])]

In [37]:
def rule_break(prev,curr,nextv): #Returns true if a rule broken 

    if np.isnan(prev): #We are at the beginning:
        if np.abs(curr-nextv) > 3:
            return True 
    if np.isnan(nextv): #We are at the end
        if np.abs(prev-curr) > 3:
            return True
    if prev == curr or curr == nextv: #Check if they're the same 
        return True
    if (prev - curr <= 0) and (curr - nextv >=0):
        return True
    if (prev - curr >=0) and (curr - nextv <=0):
        return True 
    if np.abs(prev-curr)>3:
        return True
    if np.abs(curr-nextv) >3:
        return True
    else:
        return False # Pass

In [111]:
# A dirty method of dampening 

safe = 0
breaking_list = []
test = [np.array([7,6,4,2,1]),
        np.array([1,2,7,8,9]),
        np.array([9,7,6,2,1]),
        np.array([1,3,2,4,5]),
        np.array([8,6,4,4,1]),
        np.array([1,3,6,7,9])]
def satisfies_rules(report):
    for index in range(len(report)-1):
        if index == 0: #At the beginning 
            if rule_break(np.nan,report[index],report[index+1]):
                
                return False
                break
            else:
                continue
        else: #Not at beginning 
            if rule_break(report[index-1],report[index],report[index+1]):
                return False
                break
            else:
                continue

    return True
for report in d2_input:
    if satisfies_rules(report):
        safe +=1
    else:
        for i in range(len(report)):
            if satisfies_rules(np.delete(report,i)):
                safe += 1
                break
safe
                

493

In [ ]:
rule_break(

In [82]:
#Dampening
unsafe = 0
breaking_list = []
test = [np.array([7,6,4,2,1]),
        np.array([1,2,7,8,9]),
        np.array([9,7,6,2,1]),
        np.array([1,3,2,4,5]),
        np.array([8,6,4,4,1]),
        np.array([1,3,6,7,9])]
for report in test:
    for index in range(len(report)):
        try:
            prev = report[index-1]
        except: 
            prev = np.nan
        curr = report[index]
        try:
            nex = report[index+1]
        except:
            nex = np.nan
        currd = nex
        try:
            nexd = report[index+2]
        except:
            nexd = np.nan

        if rule_break(prev,curr,nex):
            if rule_break(prev,currd,nexd):
                unsafe +=1
                breaking_list.append(report)
                break
       
                continue

safe = len(test) - unsafe
print(safe)
print(breaking_list)

1
[array([7, 6, 4, 2, 1]), array([1, 2, 7, 8, 9]), array([9, 7, 6, 2, 1]), array([8, 6, 4, 4, 1]), array([1, 3, 6, 7, 9])]


In [89]:
unsafe = 0
breaking_list = []
test = [np.array([7,6,4,2,1]),
        np.array([1,2,7,8,9]),
        np.array([9,7,6,2,1]),
        np.array([1,3,2,4,5]),
        np.array([8,6,4,4,1]),
        np.array([1,3,6,7,9])]
report_num = 0
for report in d2_input:
    report_num += 1
    for index in range(len(report)):
        if index == 0:
            prev = np.nan
    
        else:
            prev = report[index-1]
            
        curr = report[index]
        try:
            nex = report[index+1]
        except:
            nex = np.nan
        currd = nex
        try:
            nexd = report[index+2]
        except:
            nexd = np.nan
    
        if rule_break(prev,curr,nex):
            #print(index, 'Rule break in report', report_num)
            if rule_break(prev,currd,nexd):
                unsafe +=1
                breaking_list.append(report)
                #print(index, 'Rule break with damp:', prev, currd, nexd)
                break
       
        continue

safe = len(d2_input) - unsafe
print(safe)
#print(breaking_list)

483


In [71]:
# Dampening
unsafe = 0
breaking_list = []
test = [np.array([7,6,4,2,1]),
        np.array([1,2,7,8,9]),
        np.array([9,7,6,2,1]),
        np.array([1,3,2,4,5]),
        np.array([8,6,4,4,1]),
        np.array([1,3,6,7,9])]
for report in test:
    for index in range(len(report)):
        print(index)
        #Beginning and end edge cases 
        if index == 0:
            if rule_break(np.nan,report[index],report[index+1]):
                if rule_break(np.nan,report[index+1],report[index+2]):
                    unsafe += 1
                    break
        if index == len(report) -1:
            if rule_break(report[index-1],report[index],np.nan):
                if rule_break(report[index-1],np.nan,np.nan):
                    unsafe += 1
                    break
        #All other cases
        else: 
            if rule_break(report[index-1],report[index],report[index+1]): 
                #Try Dampening 
                if rule_break(report[index-1],report[index+1],report[index+2]):
                    unsafe += 1
                    breaking_list.append(report)
                    break
                                  
                else:
                    continue
            else:
                continue

safe = len(d2_input) - unsafe
print(safe)

0
0
0
0
1
2
3
4
0
0
995


In [42]:
rule_break(np.nan,np.nan,5)

False

In [58]:
import numpy as np

# Rule-breaking counter
unsafe = 0
breaking_list = []

# Test arrays
test = [
    np.array([7, 6, 4, 2, 1]),
    np.array([1, 2, 7, 8, 9]),
    np.array([9, 7, 6, 2, 1]),
    np.array([1, 3, 2, 4, 5]),
    np.array([8, 6, 4, 4, 1]),
    np.array([1, 3, 6, 7, 9])
]

# Iterate through test cases
for report in d2_input:
    for index in range(len(report)):
        # Beginning edge case
        if index == 0:
            if rule_break(np.nan, report[index], report[index+1]):
                unsafe += 1
                breaking_list.append((report, index))
                break
        
        # End edge case
        elif index == len(report) - 1:
            if rule_break(report[index-1], report[index], np.nan):
                unsafe += 1
                breaking_list.append((report, index))
                break
        
        # All other cases
        else:
            if rule_break(report[index-1], report[index], report[index+1]):
                # Try Dampening
                if index + 2 < len(report) and rule_break(report[index-1], report[index+1], report[index+2]):
                    unsafe += 1
                    breaking_list.append((report, index))
                    break
                else:
                    continue

# Calculate the number of safe reports
safe = len(d2_input) - unsafe

# Output results
print(f"Safe reports: {safe}")
#print(f"Breaking reports: {len(breaking_list)}")
#print(f"Details of breaking reports: {breaking_list}")

Safe reports: 465


In [101]:
def is_safe(report):
    for i in range(len(report) - 1):  # Iterate over consecutive pairs
        prev = report[i]
        curr = report[i + 1]
        try:
            damp = report[i +2]
        except:
            damp = np.nan

        # Rule 1: No plateaus
        if prev == curr:
            if prev == damp:
                return False

        # Rule 2: Consistent trend
        if i > 0 :  # Compare trend with the previous pair
            if (report[i - 1] < prev and prev > curr) or (report[i - 1] > prev and prev < curr):
                if (report[i-1] < curr and curr > damp) or (report[i-1] > curr and curr < damp):
                    
                    return False

        # Rule 3: Magnitude of change
        if abs(prev - curr) > 3:
            if abs(prev - damp) >3:
        
                return False
    return True

In [102]:
safe = 0 
for report in d2_input:
    if is_safe(report):
        safe += 1

safe

591